apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: dungeon-secrets
spec:
  tokenSecret:
    name: doppler-token
  managedSecret:
    name: dungeon-app-secrets
    type: Opaque
  config: stg
  resyncSeconds: 60
