apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

labels:
  - pairs:
      app.kubernetes.io/name: dungeon
      app.kubernetes.io/part-of: dungeon-minus-one

images:
  - name: registry.digitalocean.com/dungeon-minus-one/dungeon-minus-one
    newTag: v1.4.1
